name: wake-api-test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WIT_WORKSPACE: workspace

    steps:
      - name: 'Init Wit Workspace'
        uses: sifive/wit/actions/wit@v0.13.1
        with:
          command: init
          arguments: |
            ${{ env.WIT_WORKSPACE }}
            -a git@github.com:sifive/freedom-e-sdk.git::${{ github.sha }}
            -a git@github.com:sifive/environment-blockci-sifive.git::0.7.1
          force_github_https: true

      - name: 'Run Wake API Test'
        uses: sifive/environment-blockci-sifive/actions/wake@0.7.1
        with:
          workspace: ${{ env.WIT_WORKSPACE }}
          command: -v --in freedom_e_sdk_test -x 'testFreedomESDKWakeAPI Unit'
